name: api-beats-worker

replicaCount: 1

image:
  repository: registry.digitalocean.com/cloudintegration/doc2api
  tag: latest  # Will be overridden by CI/CD
  pullPolicy: Always

imagePullSecrets:
  - name: cloudintegration

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false

containerPort: 8080

command:
  - /bin/bash
  - -c
  - |
    echo "📅 Container time (UTC): $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "📍 Timezone: $TZ"
    export TZ=UTC
    echo "Starting Celery Beat Worker..."
    exec /app/venv/bin/celery -A app.app worker --loglevel=info --queues=beats --concurrency=2

externalConfigmap:
  name: api

# Deployment name for Kubernetes
deploymentName: api-beats-tasks