name: api

replicaCount: 3

image:
  repository: registry.digitalocean.com/cloudintegration/doc2api
  tag: latest  # Will be overridden by CI/CD
  pullPolicy: Always

imagePullSecrets:
  - name: cloudintegration

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  class: nginx
  annotations:
    cert-manager.io/cluster-issuer: "dns-issuer"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  hosts:
    - host: dev.api.docbits.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dev-api-docbits-com-tls
      hosts:
        - dev.api.docbits.com

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 3

containerPort: 8080

externalConfigmap:
  name: api

# Deployment name for Kubernetes
deploymentName: api-service

setIngressClassByField: true