{{- if .Values.storage -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.persistentVolumeClaimName | default (include "base-api.fullname" .) }}
  labels:
    {{- include "base-api.labels" . | nindent 4 }}
  {{- if .Values.storage.keepPvc }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  {{- with .Values.storage }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  volumeMode: {{ .volumeMode | default "Filesystem" }}
  resources:
    requests:
      storage: {{ .requestedSize }}
  {{- if .className }}
  storageClassName: {{ .className }}
  {{- end }}
  {{- end }}
  {{ if .Values.storage.enableDataSource}}
  dataSource:
    kind: PersistentVolumeClaim
    name: {{ .Values.storage.persistentVolumeClaimName | default (include "base-api.fullname" .) }}
{{- end }}
{{- end }}
