{{- if or (and (kindIs "slice" .Values.service) .Values.service ) ((.Values.service).enabled) -}}
{{- range $key, $service := (ternary .Values.service (list .Values.service) (kindIs "slice" .Values.service)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.metadata.name }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.targetPort | default .Values.containerPort }}
      protocol: {{ $service.protocol }}
      name: {{ $service.name }}
    {{- if $service.extraPorts }}
    {{- toYaml $service.extraPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}