{{- if .Values.service }}
{{- $services := list }}
{{- if kindIs "slice" .Values.service }}
  {{- $services = .Values.service }}
{{- else if kindIs "map" .Values.service }}
  {{- $services = list .Values.service }}
{{- end }}
{{- range $service := $services }}
{{- if and (kindIs "map" $service) (hasKey $service "enabled") $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name | default "default-service-name" }}
  labels:
    {{- include "base.labels" $ | nindent 6 }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    - port: {{ $service.port | default 80 }}
      targetPort: {{ $service.targetPort | default $.Values.containerPort | default 8080 }}
      protocol: {{ $service.protocol | default "TCP" }}
      name: {{ $service.name | default "default-port-name" }}
    {{- if $service.extraPorts }}
    {{- toYaml $service.extraPorts | nindent 6 }}
    {{- end }}
  selector:
    {{- include "base.selectorLabels" $ | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}